#!/bin/sh

FILTER=.md
EXTENSION=tex
#INPUTFILE=cheat-sheet-git.md

# set paths
OUTPUTPATH=bin
INPUTPATH=source/*$FILTER

# set formats for pandoc
INPUTFORMAT=markdown
OUTPUTFORMAT=latex

# set name of auto-generated file
AUTOGENERATEDFILE=auto-generated-include.tex

# directory for auto-generated files
rm -rf $OUTPUTPATH
mkdir -p $OUTPUTPATH

# iterate about all file in directory $INPUTPATH
for file in $INPUTPATH
do

	# set name of output file
	OUTPUTFILE=$OUTPUTPATH/`basename $file`.$EXTENSION

	# convert
	pandoc $file -f $INPUTFORMAT -t $OUTPUTFORMAT -s -o $OUTPUTFILE
	echo "- Converted input file '$file' to output file '$OUTPUTFILE'. Done!"

	# add file to auto-generated include file for latex
	echo "\\input{$OUTPUTFILE}" >> $OUTPUTPATH/$AUTOGENERATEDFILE
#	echo '\\newpage'            >> $OUTPUTPATH/$AUTOGENERATEDFILE
	echo "- Added output file '$OUTPUTFILE' to '$AUTOGENERATEDFILE'. Done!"

	# format latex 
	sed -i '1,/\\begin{document}/ d' $OUTPUTFILE				# Delete all until \begin{document}
	sed -i 's/\\begin{verbatim}/\\begin{lstlisting}/g' $OUTPUTFILE		# Replace verbatim to lstlisting
	sed -i 's/\\end{verbatim}/\\end{lstlisting}/g' $OUTPUTFILE	  	# 	
	sed -i 's/\\href{/\\footnote{/g' $OUTPUTFILE				# Replace href with footnote 
	sed -i 's/\\end{document}//g' $OUTPUTFILE				# Delete \end{document}
	sed -i 's/ü/\\"u/g' $OUTPUTFILE						# 
	sed -i 's/Ü/\\"U/g' $OUTPUTFILE						# 
	sed -i 's/ä/\\"a/g' $OUTPUTFILE						# 
	sed -i 's/Ä/\\"A/g' $OUTPUTFILE						# 
	sed -i 's/ö/\\"o/g' $OUTPUTFILE						# 
	sed -i 's/Ö/\\"O/g' $OUTPUTFILE						# 
	sed -i 's/ß/{\\ss}/g' $OUTPUTFILE					# 
	
done

